### ISSUE TITLE
messagePump failed due to client response Error

### ISSUE THREAD

**Issue by aesculus** [PeteRager/lennoxs30api#65]
@PeteRager Have you seen this one?

`Message pump error (S30Exception(...), "messagePump failed due to client response error [https://192.168.1.224/Messages/Aesculus_Downstairs/Retrieve] ClientResponseError Error while executing request: [Content-Length can't be present with Transfer-Encoding:\n\n  b'4B\\r'\n    ^]: error=<class 'aiohttp.client_exceptions.ClientResponseError'>, resp.status=[400], resp.request_info=[RequestInfo(url=URL('https://192.168.1.224/Messages/Aesculus_Downstairs/Retrieve?Direction=Oldest-to-Newest&MessageCount=10&StartTime=1&LongPollingTimeout=5'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.1.224', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.5')>, real_url=URL('https://192.168.1.224/Messages/Aesculus_Downstairs/Retrieve?Direction=Oldest-to-Newest&MessageCount=10&StartTime=1&LongPollingTimeout=5'))], resp.headers=[None]")`

It was working fine for 3 days and suddenly it just started this on both of my S30's. Stopping and starting the Docker container resolved the problem.

EDIT: It appears it was only one S30. It is the one with two zones and this was the primary. Did not see any errors on the secondary but its data did not change so assume that it was not getting data either.

**Comment by PeteRager** [comment]
Yes those happen periodically and randomly.  Seem to be more likely on a system that has diagnostics enabled and is connected to the internet.  Solution is to restart the connection.  In rare cases a controller reset may be needed.

Here's where the error is trapped

https://github.com/PeteRager/lennoxs30api/blob/19549dea5ed0ac73679b645bb774bf8f6b57905e/lennoxs30api/s30exception.py#L56

https://github.com/PeteRager/lennoxs30/blob/25ce86f288fa4b94aa6096136efd35039467186d/custom_components/lennoxs30/__init__.py#L950

https://github.com/PeteRager/lennoxs30api/blob/19549dea5ed0ac73679b645bb774bf8f6b57905e/lennoxs30api/s30api_async.py#L715

**Comment by aesculus** [comment]
OK. Thanks for the info. I guess I will need to add some logic for that error and do a shutdown and restart.

FYI my system is locally connected and diagnostics is off.

**Comment by aesculus** [comment]
Being a neophyte how would you suggest I trap and recover from this? How do I see what code is delivered within the 'e' error and I know I should call a shutdown but how best to restart?

```
async def message_pump_task(s30api: s30api_async) -> None:
    global running
    
    try:
        # Login and establish connection
        await s30api.serverConnect()
        # For each S30 found, initiate the data subscriptions.
        for lsystem in s30api.system_list:
            await s30api.subscribe(lsystem)
    # Catch errors and exit this task.
    except S30Exception as e:
        sys.stderr.write("Failed to connect error " + str(e) + "\n")
        return
    while running:
        # Checks for new messages and processes them which may update the state of zones, etc.
        try:
            await s30api.messagePump()
            await asyncio.sleep(1)
        # Intermittent errors due to Lennox servers, etc, may occur, log and keep pumping.
        except S30Exception as e:
            sys.stderr.write("Message pump error " + str(e) + "\n")
    else:
        await s30api.shutdown()
        sys.stderr.write("shutdown\n")
```

In the exception:

```
if e.code == ?:
    await s30api.shutdown()
```
    then what do I call here? just a await s30api.serverConnect() or do I need to call this routine again to get the subscribe working?

**Comment by PeteRager** [comment]
That's a good question.  The HASS integration calls serverconnect then reestablishes the subscriptions. 

https://github.com/PeteRager/lennoxs30/blob/25ce86f288fa4b94aa6096136efd35039467186d/custom_components/lennoxs30/__init__.py#L784

**Comment by aesculus** [comment]
Hah. In the HASS message pump I find this:

# Since the S30 will close connections and kill the subscription periodically, these errors are expected.  Log as warnings

So this should be expected after so many hours I guess.

And the recovery does need a resubscription based on what I see in the HASS code.  So my question is more of a python question I think.

I know I need to kill the subscription and restart and subscribe. That would seem to be to recall my message_pump_task above. But I am worried about being recursive.

So in my exception do I:
call a shutdown
then recall the message_pump_task routine
then return to exit the old routine where the new one will take over

or

call a shutdown
then do a connect and subscribe

but if the later will I still be working within the message_pump_task routine and have exception tracking for the next time this occurs or will my subscribes just be rogue?

**Comment by PeteRager** [comment]
I think you have a number of options.

a) When your message pump task encounters an exception, have it launch a new message pump task and exit. 

b) Put another while running loop around the try: , exit the inner loop with a break; which will then cause existing logic to reconnect to happen

Another consideration is to add a delay before retrying.  What the HASS integration does is immediately tries to reconnect and if that reconnect fails then it delays for 30 seconds and tries again.

**Comment by aesculus** [comment]
I like this:

`b) Put another while running loop around the try: , exit the inner loop with a break; which will then cause existing logic to reconnect to happen`

But shouldn't I call a shutdown before I call the break? 

And I probably need some sort of flag to terminate the mess in case I am not successful in the reconnects like with the delay mentioned. I'll see what I can steal from the HASS code. :-)

**Comment by PeteRager** [comment]
You could call disconnect, don't know that it is necessary as you've been disconnected already and are reconnecting immediately. The main purpose of calling disconnect is to cancel the subscription so the internal queues don't overflow.  As a side note, calling disconnect on the S40 (after the april firmware updates) renders the S40 un-connectable.

Basically you want a state machine with two steps:

1.  Connect/Subscribe

When in this state try to connect and subscribe; if that fails; sleep for X seconds and retry indefinitely AND perhaps send yourself a notification after Y attempts .

2. MessagePump

When in this state pump messages; when an exception occurs go to the Connect/Subscribe state.  When a shutdown occurs got to third state

3. Shutdown

Shutdown the connection; exit the task.

**Comment by aesculus** [comment]
OK. I'll see if I can code that up.

**Comment by aesculus** [comment]
@PeteRager 

Does this look reasonable to you? I will have to run it for 36 hours before I know if the error trap is the right one and it behaves properly.

```
async def message_pump_task(s30api: s30api_async) -> None:
    global running
    connected = True
    retries = 0
    while connected:
        if retries > 10:
            sys.stderr.write("Retries exceeded. Shutting down.\n")
            running = False
            break;
        try:
            # Login and establish connection
            await s30api.serverConnect()
            # For each S30 found, initiate the data subscriptions.
            for lsystem in s30api.system_list:
                await s30api.subscribe(lsystem)
        # Catch errors and exit this task.
        except S30Exception as e:
            sys.stderr.write("Failed to connect error " + str(e) + "\n")
            return
        while running:
            # Checks for new messages and processes them which may update the state of zones, etc.
            try:
                await s30api.messagePump()
                await asyncio.sleep(1)
            # Intermittent errors due to Lennox servers, etc, may occur, log and keep pumping.
            except S30Exception as e:
                sys.stderr.write("Message pump error " + str(e) + "\n")
                retries += 1
                if e.status == 400:
                    await s30api.shutdown()
                    await asyncio.sleep(10)
                    break
            retries = 0
        else:
            connected = False
            await s30api.shutdown()
            sys.stderr.write("shutdown\n")
    else:
        running = False
```

**Comment by aesculus** [comment]
Well I tried various logic streams and never got a successful trap. I have now realized that you cannot depend on metrics.last_receive_time to stay the same or even vary when metrics.message_count.

So I have now moved to adding and resetting a simple counter when the metrics.message_count is the same. After about 1 minute of that not changing, I decide to take action and reset the connection to the S30.

The last test I did where I had a small flaw in my code took 3 days to reach my threshold. So it takes a bit of time for each test cycle.

In the mean time the Grafana dashboard is fully functional.

**Comment by aesculus** [comment]
Making progress and as reported the test interval is a killer. I tried forcing both logouts and disconnects programmatically but they are not the same as when the device terminates a session.

I think I have finally created a solution that definately responds to the disconnects. I may still have some work to do on when it will not communicate after a lengthy session of communications, but that is a rare bird I have only seen once before.

An interesting aspect is when you login again after a device logout, the message count continues from where it was before the disconnection:

```
{"log":"INFO:20230926082210 system=Aesculus_Downstairs message_count = 6355 last_receive_time = 2023-09-26 08:21:49.216600+00:00\n","stream":"stderr","time":"2023-09-26T08:22:10.26021364Z"}
{"log":"INFO:Message pump error - (S30Exception(...), 'messagePump failed due Server Disconnected [https://192.168.1.224/Messages/Aesculus_Downstairs/Retrieve]')\n","stream":"stderr","time":"2023-09-26T08:22:36.586789433Z"}
{"log":"\n","stream":"stderr","time":"2023-09-26T08:22:36.586847698Z"}
{"log":"INFO:Trying to connect to Aesculus_Downstairs\n","stream":"stderr","time":"2023-09-26T08:22:36.586875238Z"}
{"log":"\n","stream":"stderr","time":"2023-09-26T08:22:36.586899305Z"}
{"log":"INFO:Updating lennox_home homeIdx [0 homeId [local] homeName [local]\n","stream":"stderr","time":"2023-09-26T08:22:36.93679041Z"}
{"log":"INFO:Update lennox_system idx [0] sysId [LCC]\n","stream":"stderr","time":"2023-09-26T08:22:36.9368483Z"}
{"log":"INFO:login Success homes [1] systems [1]\n","stream":"stderr","time":"2023-09-26T08:22:36.936985662Z"}
{"log":"INFO:20230926082310 system=Aesculus_Downstairs message_count = 6370 last_receive_time = 2023-09-26 08:23:08.695924+00:00\n","stream":"stderr","time":"2023-09-26T08:23:10.422126781Z"}
```

**Comment by PeteRager** [comment]
Those counters are tracked in the API.  If you want to reset them, there is a reset method you can call

https://github.com/PeteRager/lennoxs30api/blob/19549dea5ed0ac73679b645bb774bf8f6b57905e/lennoxs30api/metrics.py#L9

The way I tackled this in the API and HA integration was by using PyTest and then injecting the errors and looking at the results.  

https://github.com/PeteRager/lennoxs30api/blob/19549dea5ed0ac73679b645bb774bf8f6b57905e/tests/test_receive_errors.py#L19

**Comment by aesculus** [comment]
Thanks for the extra info. I think I am OK now for my two scenarios. Any other situations I should expect and trap?

I probably won't bother to reset the counter, I just thought it was interesting that it did not reset after a new login, but that is the difference I guess between being logged out vs terminating the connection.

**Comment by aesculus** [comment]
Update: For the past week my system has been running pretty reliably. Its reset itself 3 times (twice for duplication of message count and once when a system stopped communicating). Its a hack code but I think I will probably just tidy it up a bit and then run it for a number of months before doing anything more to it.
